import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "C-Four",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen"}>
        <div className="flex flex-col h-full">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
