# Generated by Django 5.1 on 2024-08-16 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombreMarca', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('correoMarca', models.EmailField(max_length=255)),
                ('passwordUsuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, max_length=255, primary_key=True, serialize=False)),
                ('correoUsuario', models.EmailField(error_messages={'invalid': 'Por favor, introduce una dirección de correo electrónico válida.', 'unique': 'Ya existe un usuario con este correo electrónico'}, max_length=255, unique=True)),
                ('passwordUsuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=255)),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadDisponible', models.IntegerField()),
                ('productoImagen', models.CharField(max_length=255)),
                ('nombreMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('nombreMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
