# Generated by Django 5.1 on 2024-08-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=255)),
                ('passwordUsuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=255)),
                ('correoUsuario', models.EmailField(max_length=255)),
                ('passwordUsuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=255)),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadDisponible', models.IntegerField()),
                ('productoImagen', models.CharField(max_length=255)),
                ('nombreMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
