# Generated by Django 5.1 on 2024-08-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_carritousuario_historialcomprausuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipoProducto',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
