# Generated by Django 5.1 on 2024-08-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_tipoproducto_delete_tipoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productoImagen',
            field=models.TextField(),
        ),
    ]
