# Generated by Django 5.1 on 2024-08-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_productoimagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosMarca',
        ),
    ]
