# Generated by Django 5.1 on 2024-08-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_productosmarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(),
        ),
    ]
