# Generated by Django 5.1 on 2024-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_precioproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcomprausuario',
            name='cantidadComprado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
